# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam justo turpis, tincidunt ac convallis id.'
location: Location
website: Website

social:
  twitter: https://twitter.com/
  google+: https://plus.google.com/
  github: https://github.com/

excerpt_link: Read More

# Miscellaneous
rss: /atom.xml
